-- Seed data for Cards table
-- Run this in the Supabase SQL Editor AFTER running the 20260321120000_admin_expansion_v2.sql migration.

INSERT INTO public.cards (text, type, points, timer) VALUES
('Do your best impression of me when I am angry. (Tuze ragavlele natak kar!)', 'fun', 1, 30),
('Speak in a weird accent for the next 2 rounds. (Bhai, agle 2 round alien language!)', 'fun', 1, NULL),
('Let your partner style your hair in the funniest way possible.', 'fun', 1, 60),
('Dance without music for 30 seconds. (Bina music ke dance kar ke dikha!)', 'fun', 1, 30),
('Read the last text you sent to your best friend out loud.', 'fun', 1, NULL),
('Try to lick your elbow. (Koparla jeebh laun dakhaw!)', 'fun', 1, 15),
('Talk without closing your mouth for the next round.', 'fun', 1, NULL),
('Post a weird status on WhatsApp for 10 minutes. (10 minute ke liye ajeeb status daal!)', 'fun', 1, 600),
('Share the exact moment you realized you liked me. (Maza var prem kadhi basla te sang.)', 'romantic', 1, NULL),
('Give me a 1-minute foot or hand massage.', 'romantic', 1, 60),
('Describe my best physical feature in loving detail. (Meri sabse achi baat batao!)', 'romantic', 1, NULL),
('Stare into my eyes without blinking for 30 seconds. (Najar hathavli tar harla!)', 'romantic', 1, 30),
('Sing a romantic Bollywood song for me. (Pyaar wala gaana gaa ke suna!)', 'romantic', 1, NULL),
('Tell me about a dream you had about us.', 'romantic', 1, NULL),
('Recreate our first hug or kiss. (Pahila mithi kashi marli hoti, dakhav!)', 'romantic', 1, NULL),
('Write a quick 4-line poem about me. (Mazya vishayi 4 oli chi kavita kar.)', 'romantic', 1, 120),
('Kiss me on the neck. (Manevar pappa ghe!)', 'spicy', 1, NULL),
('Whisper your deepest fantasy into my ear. (Kaanat tuze secret fantasies sang.)', 'spicy', 1, NULL),
('Take off one piece of clothing. (Ek kapda nikaal!)', 'spicy', 1, NULL),
('Give me a passionate kiss for 10 seconds.', 'spicy', 1, 10),
('Let me blindfold you and feed you something sweet.', 'spicy', 1, NULL),
('Trace my lips with your fingers. (Hotanvar bot firaw.)', 'spicy', 1, NULL),
('Tell me the hottest thing I wear. (Mi kontya dress madhe hot disto/diste?)', 'spicy', 1, NULL),
('Give me a sensuous 2-minute back rub.', 'spicy', 1, 120),
('Send me a voice note saying "I love you" in the sexiest voice.', 'ldr', 1, NULL),
('Send me a picture of the exact clothes you are wearing right now. (Aata je ghaltoyes tyacha photo pathaw!)', 'ldr', 1, NULL),
('Blow me a kiss through the screen.', 'ldr', 1, NULL),
('Order a small dessert for me right now! (Swiggy/Zomato varun order kar!)', 'ldr', 1, NULL),
('Keep the video call completely silent for 1 minute while we just look at each other.', 'ldr', 1, 60),
('Describe what we would be doing right now if we were together. (Aapan ektra aslo asto tar kay kela asta?)', 'ldr', 1, NULL),
('Pretend to be a gym bro explaining why I desperately need to hit my protein goal today 🍗💪', 'fun', 1, 45),
('Act out a dramatic, slow-motion death scene from BGMI right now 🎮💀', 'fun', 1, NULL),
('Explain a complex coding bug to me using only cheesy romantic pickup lines 💻❤️', 'fun', 1, 60),
('Do your absolute best impression of someone aggressively haggling for clothes on FC Road 🛍️😂', 'fun', 1, NULL),
('Try to lick your elbow while maintaining intense eye contact with me 👀👅', 'fun', 1, 15),
('Speak entirely in rhymes for the next 2 minutes 🎤🎶', 'fun', 1, 120),
('Show me the last meme you saved on your phone without giving any context 📱🤡', 'fun', 1, NULL),
('Balance your phone on your head and walk across the room without dropping it 🚶‍♂️📱', 'fun', 1, NULL),
('Send me a playlist of 3 songs that instantly remind you of me 🎵🥺', 'romantic', 1, NULL),
('Tell me the exact moment you realized you had feelings for me ✨💖', 'romantic', 1, NULL),
('Write a quick 4-line poem about my smile right now ✍️😊', 'romantic', 1, 60),
('Name a small, random habit of mine that you absolutely adore 🕵️‍♀️💘', 'romantic', 1, NULL),
('Stare into my eyes (or my photo) for 30 seconds without saying a word 👁️❤️', 'romantic', 1, 30),
('Tell me about a dream you had about us that you never shared 🌙💭', 'romantic', 1, NULL),
('Plan out our dream vacation itinerary in 3 sentences ✈️🏝️', 'romantic', 1, NULL),
('Describe exactly what you’d do if we were alone in a locked elevator right now 🛗🔥', 'spicy', 1, NULL),
('Send a voice note whispering your favorite physical feature of mine 🤫💦', 'spicy', 1, 20),
('Rate your current thoughts about me from 1-10 on the spicy scale 🌶️🥵', 'spicy', 1, NULL),
('Tell me the most adventurous place you’d want to make out with me 🗺️💋', 'spicy', 1, NULL),
('Show me the outfit you’d wear if you wanted to guarantee I couldn’t keep my hands off you 👗👔🔥', 'spicy', 1, NULL),
('Describe the way you want me to touch you right now without using any banned words 🤐✨', 'spicy', 1, NULL),
('Send the most suggestive emoji combo you can think of and let me guess what it means 🍆🍑💦', 'spicy', 1, NULL),
('Order me a surprise little dessert on Swiggy or Zomato right now 🍰🛵', 'ldr', 1, NULL),
('Show me the exact view from your window right this second 🪟🏙️', 'ldr', 1, NULL),
('Take a picture of the exact spot where you wish I was sitting right now 🪑👻', 'ldr', 1, NULL),
('Voice note: Tell me how you would wake me up if we were in the same bed tomorrow morning 🛌🌅', 'ldr', 1, NULL),
('Send a quick video spinning around in your room so I can feel like I’m there 🌀📱', 'ldr', 1, NULL),
('Write my name somewhere on your body with a pen and send a pic 🖊️📸', 'ldr', 1, NULL),
('Find an item in your room that reminds you of me and explain why 🧸💭', 'ldr', 1, NULL),
('Record a 10-second video pretending you are giving me a massive hug 🤗🫂', 'ldr', 1, NULL),
('Sing a Bollywood song loudly but replace every "Pyaar" or "Dil" with "Paneer" 🧀🎤', 'fun', 1, 30),
('Explain how to build a custom PC, but make the motherboard and SSD sound like two star-crossed lovers 🖥️❤️', 'fun', 1, 60),
('Do your best impression of a strict Indian parent catching us holding hands in public 😡😂', 'fun', 1, NULL),
('Let me give you a silly new nickname and you have to respond to it for the next 24 hours 🤪', 'fun', 1, NULL),
('Pretend your Samsung phone is a walkie-talkie and report a "romantic emergency" to headquarters 📱👮‍♂️', 'fun', 1, 45),
('Do 10 squats while singing "Chammak Challo" at the top of your lungs 💃🍑', 'fun', 1, NULL),
('Talk without opening your teeth for the next 2 minutes 🤐⏱️', 'fun', 1, 120),
('Put an ice cube down your shirt and try to maintain a totally straight face 🧊😐', 'fun', 1, 30),
('Let me pick a random emoji to put on your WhatsApp status for the next hour without any context 📱🤷‍♂️', 'fun', 1, NULL),
('Put your shirt on inside out for the rest of our conversation 👕🙃', 'fun', 1, NULL),
('Try to lick your own nose while winking at me 👅👃😉', 'fun', 1, 15),
('Pitch me a terrible idea for a mobile app like you are on Shark Tank 🦈📱', 'fun', 1, 60),
('Pretend you are an influencer doing a grand tour of your extremely messy room 🤳🗑️', 'fun', 1, NULL),
('Do a dramatic, soap-opera reading of the last text message you received 📖😂', 'fun', 1, NULL),
('Speak only in a robotic voice for the next 3 minutes 🤖⏱️', 'fun', 1, 180),
('Describe our relationship using only 3 movie titles 🍿❤️', 'romantic', 1, NULL),
('Tell me the exact moment you knew you had fallen for me 🥰✨', 'romantic', 1, NULL),
('Plan a dream group motorcycle trip for us on RideTogether, including where we stop for chai 🏍️☕', 'romantic', 1, NULL),
('Write my name on your wrist with a pen and keep it there all day 🖊️💕', 'romantic', 1, NULL),
('Serenade me with a romantic song for 30 seconds, no matter how bad your voice is 🎶🎤', 'romantic', 1, 30),
('Tell me your absolute favorite physical feature of mine and blow a kiss to it 😘', 'romantic', 1, NULL),
('Describe what a perfect lazy Sunday morning looks like with me 🏡☕', 'romantic', 1, NULL),
('Stare into my eyes (or my photo) without blinking or smiling for 60 seconds 👀⏱️', 'romantic', 1, 60),
('Give me a 5-minute virtual massage by describing exactly how you would do it 💆‍♂️💆‍♀️', 'romantic', 1, NULL),
('Recreate the pose from the first picture we ever took together 📸🔄', 'romantic', 1, NULL),
('Tell me a tiny, adorable secret you’ve never told anyone else before 🤫❤️', 'romantic', 1, NULL),
('Make a list of 5 things you appreciate most about me and read it aloud with full emotion 📜🥺', 'romantic', 1, NULL),
('Tell me the story of our first date purely from your perspective 📖🌹', 'romantic', 1, NULL),
('Dedicate a classic romantic Bollywood dialogue to me right now 🎬💘', 'romantic', 1, NULL),
('Hold your hand up to the screen and tell me why I am your favorite person 🤝💖', 'romantic', 1, NULL),
('Tell me your biggest turn-on that you’ve never fully confessed before 🤫🔥', 'spicy', 1, NULL),
('Describe exactly what you would do if I was wearing your favorite outfit right now 👗🥵', 'spicy', 1, 60),
('Send a voice note of your best "bedroom voice" whispering my name 🎙️💦', 'spicy', 1, NULL),
('Tell me the dirtiest thought you’ve had about us while at the gym 🏋️‍♂️😈', 'spicy', 1, NULL),
('Send a picture of you biting your lip while looking right at the camera 🫦📸', 'spicy', 1, NULL),
('Rate my kissing skills from 1-10 and explain exactly how I earned that rating 💋📈', 'spicy', 1, NULL),
('Tell me where your favorite unexpected place to be kissed is 🎯😘', 'spicy', 1, NULL),
('Describe a new position or fantasy you want to try next time we have absolute privacy 🤸‍♀️🔥', 'spicy', 1, NULL),
('Unbutton one button or take off one piece of clothing right now 👚👀', 'spicy', 1, NULL),
('Tell me what the most sensitive spot on your body is and how you want me to touch it 🪶✨', 'spicy', 1, NULL),
('Send me a risky text message that you would be terrified if anyone else saw 📱😳', 'spicy', 1, NULL),
('Whisper exactly what you want me to do to you tonight in under 15 seconds 🤫👂', 'spicy', 1, 15),
('Show me the sexiest piece of clothing you own and tell me when you plan to wear it 👙👔', 'spicy', 1, NULL),
('Tell me the exact explicit thought you had the first time we kissed 💭🔥', 'spicy', 1, NULL),
('Slowly eat a piece of fruit or chocolate while maintaining intense eye contact with me 🍓🍫', 'spicy', 1, 30),
('Send me a 5-second video of your current view, no matter how boring it is 🪟📱', 'ldr', 1, NULL),
('Order me a surprise cheat-meal treat on Zomato or Swiggy right now without telling me what it is 🍩🛵', 'ldr', 1, NULL),
('Take a selfie in the exact spot you wish I was sitting next to you right now 🪑📸', 'ldr', 1, NULL),
('Send a voice note of you kissing the microphone 3 times slowly 💋🎙️', 'ldr', 1, NULL),
('Write a 3-line love letter and send a picture of it handwritten on paper ✍️💌', 'ldr', 1, 120),
('Change into an outfit that has my favorite color in it for the rest of our call 👕🎨', 'ldr', 1, NULL),
('Log into BGMI with me right now and protect me at all costs during the match 🎮🛡️', 'ldr', 1, NULL),
('Send a picture of the exact spot on your bed where you wish we were cuddling right now 🛏️🥺', 'ldr', 1, NULL),
('Give me a virtual house tour on video call, but pretend you are a fancy real estate agent 🏠🤵', 'ldr', 1, NULL),
('Send me a picture of the sky above you right now so we can share the same view ☁️🌤️', 'ldr', 1, NULL),
('Record yourself saying a soft "Good morning" so I can wake up to it tomorrow 🌅🎧', 'ldr', 1, NULL),
('Find an object in your room that instantly reminds you of me and explain why 🧸💭', 'ldr', 1, NULL),
('Share your screen and let me pick the next YouTube video we watch together 💻▶️', 'ldr', 1, NULL),
('Send me a screenshot of your home screen right now so I can judge your app layout 📱🔋', 'ldr', 1, NULL),
('Trace my initial on your hand and send me a picture of it ✍️✋', 'ldr', 1, NULL),
('Try to explain the plot of your favorite movie while holding a plank ⏱️🎬', 'fun', 1, 60),
('Do 15 pushups and shout out a different Indian street food on each rep! 🥟🏋️‍♂️', 'fun', 1, NULL),
('Talk like a seasoned Pune rickshaw driver negotiating a fare for the next 2 minutes 🛺😎', 'fun', 1, 120),
('Show me the most embarrassing photo in your phone\'s gallery right now 📸🙈', 'fun', 1, NULL),
('Try to juggle 3 small objects (like rolled-up socks) for 30 seconds 🤹‍♂️🧦', 'fun', 1, 30),
('Speak in an exaggerated British accent until your next turn ☕💂‍♂️', 'fun', 1, NULL),
('Pretend your phone is a dumbbell and do slow bicep curls while making intense eye contact 💪📱', 'fun', 1, NULL),
('Explain how an ORM database works but make it sound like a dramatic reality TV show 💾📺', 'fun', 1, 60),
('Put a piece of ice in your mouth and try to sing a popular BGMI lobby song 🧊🎮', 'fun', 1, NULL),
('Draw a funny face on your thumb and make it lip-sync to a song of my choice 👍🎤', 'fun', 1, NULL),
('Wear your socks on your hands for the next three rounds 🧦👐', 'fun', 1, NULL),
('Blindfold yourself and try to guess what object I\'m describing in your room 🙈🕵️‍♂️', 'fun', 1, NULL);
('\nOpen your map app and find the exact distance between us right now. Send the screenshot! 🗺️📏', 'ldr', 1, NULL),
('Do a trust fall onto your bed while imagining I\'m there to catch you 🛏️🫂', 'ldr', 1, NULL),
('Send me a quick voice note of your current background noise (traffic, fan, silence) 🎧🌃', 'ldr', 1, NULL),
('Make a cup of coffee or tea right now and take the first sip "with" me ☕🍵', 'ldr', 1, NULL),
('Find the softest blanket or hoodie in your room, wrap it around yourself, and pretend it\'s a hug from me 🧥🤗', 'ldr', 1, NULL),
('Go to your window and describe the first interesting thing you see outside 🪟👀', 'ldr', 1, NULL),
('Send me a live photo/boomerang of you blowing a kiss to the camera 💋🤳', 'ldr', 1, NULL),
('Order a small midnight snack for yourself and tell me what you got 🍕🍟', 'ldr', 1, NULL),
('Share your screen and let\'s pick a new game or app we can both download and play together right now 📲🎮', 'ldr', 1, NULL),
('Tell me what the weather is like there and how it makes you feel right now ⛈️☀️', 'ldr', 1, NULL),
('Leave your phone on the pillow next to you for the next 2 minutes so we can just "lay" together 🛏️📱', 'ldr', 1, 120),
('Send me a picture of the shoes you wore today so I can imagine walking beside you 👟👣', 'ldr', 1, NULL);
