-- Migration: AI-generated dares storage + ratings
-- Date: 2026-08-22
-- Description:
--   Stores dares generated by the Groq-backed Edge Function `groq-ai-dare`,
--   tied to the user who created them, with an optional rating so good dares can
--   be surfaced later. RLS is own-row (admins can read/delete all). The Groq API
--   key lives only as a Supabase secret used by the Edge Function — never in the
--   client and never in this table.

CREATE TABLE IF NOT EXISTS public.ai_dares (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  prompt     text,
  vibe       text,
  intensity  integer DEFAULT 2 CHECK (intensity BETWEEN 1 AND 3),
  mood       text,
  text       text NOT NULL,
  source     text NOT NULL DEFAULT 'ai',          -- 'ai' | 'local'
  rating     integer NOT NULL DEFAULT 0 CHECK (rating IN (-1, 0, 1)), -- -1 down, 0 none, 1 up
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_dares_user_created ON public.ai_dares(user_id, created_at DESC);

ALTER TABLE public.ai_dares ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "ai_dares_select_own" ON public.ai_dares;
CREATE POLICY "ai_dares_select_own" ON public.ai_dares
  FOR SELECT TO authenticated
  USING (auth.uid() = user_id OR public.is_admin());

DROP POLICY IF EXISTS "ai_dares_insert_own" ON public.ai_dares;
CREATE POLICY "ai_dares_insert_own" ON public.ai_dares
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "ai_dares_update_own" ON public.ai_dares;
CREATE POLICY "ai_dares_update_own" ON public.ai_dares
  FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "ai_dares_delete_own" ON public.ai_dares;
CREATE POLICY "ai_dares_delete_own" ON public.ai_dares
  FOR DELETE TO authenticated
  USING (auth.uid() = user_id OR public.is_admin());
